name: "On Tag Release on GitHub"
env:
    REPO_NAME: "setup_logging"
    RUN_TESTS: true
    RUST_VERSION: "1.80"
on:
    push:
        tags:
            # -   "[0-9]+.[0-9]+.[0-9]+"
            -   "*" # execute every time tag is pushed

jobs:
    datetime:
        name: "Get Current Datetime"
        env:
            working-directory: ${{github.workspace}}
        runs-on: "ubuntu-latest"

        steps:
            -   name: "NOW"
                id: "now"
                run: "echo \"NOW=$(date +'%Y-%m-%dT%H:%M:%S')\" >> $GITHUB_OUTPUT"  # get datetime, save in NOW, push to output

            -   name: "TODAY"
                id: "today"
                run: "echo \"TODAY=$(date +'%Y-%m-%d')\" >> $GITHUB_OUTPUT" # get date, save in TODAY, push to output

        outputs:    # set step output as job output so other jobs can access
            NOW: ${{steps.now.outputs.NOW}}
            TODAY: ${{steps.today.outputs.TODAY}}


    test:
        name: "Run Tests"
        env:
            working-directory: ${{github.workspace}}
        runs-on: "ubuntu-latest"

        steps:
            -   name: "Checkout Repository"
                uses: "actions/checkout@v4" # makes repository structure available

            -   name: "Install Rust"
                uses: "actions-rust-lang/setup-rust-toolchain@v1"
                with:
                    toolchain: ${{env.RUST_VERSION}}

            -   name: "Check Project Version and Tag Match"
                run: |
                    project_version=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version')
                    tag=${GITHUB_REF#refs/tags/*}
                    if [ "$project_version" == "$tag" ]; then
                        exit 0
                    else
                        exit 1
                    fi

            -   name: "Run Tests"
                if: ${{env.RUN_TESTS == 'true'}}
                run: "cargo test"


    create_release:
        name: "Create Release on Github"
        env:
            working-directory: ${{github.workspace}}
        needs: ["datetime", "test"]
        runs-on: "ubuntu-latest"

        steps:
            -   name: "Create Release"
                env:
                    GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
                id: "create_release"
                uses: "actions/create-release@v1"                                                       # function that creates release
                with:                                                                                   # parameters
                    body:                                                                               # release text
                    draft: false
                    prerelease: false
                    release_name: ${{needs.datetime.outputs.TODAY}} ${{env.REPO_NAME}} ${{github.ref}}  # release title
                    tag_name: ${{github.ref}}                                                           # release tag